### ISSUE TITLE
Incomplete include search paths in the Clang-16/LLVM-16 package

### ISSUE THREAD

**Issue by johnsonjh** [haikuports/haikuports#9407]
Greetings!

First off, thank you for the much improved LLVM 16.0.6 package, which fixes quite a few problems regarding the C search paths.  However, there are a few rough spots regarding C++ support, which I hadn't tested until now.

Attempting to build a C++20 program, for example:

```sh
> clang++ -MMD -std=c++20  -Wall -Wextra -Wpedantic -Iinclude -fPIC -O3 -DNDEBUG -D_FORTIFY_SOURCE=2  -Iinclude -c -o build/obj/tests/tests++.o tests/tests++.cc
In file included from tests/tests++.cc:26:
In file included from tests/tests++.hh:29:
include/sir.hh:33:11: fatal error: 'type_traits' file not found
# include <type_traits>
          ^~~~~~~~~~~~~
1 error generated.
```

Luckily, Clang and GCC both support the support the same syntax and output format to query the search path, so it's easy to see the differences from the system GCC:

```diff
> diff -U0 \
    <(clang++ -Wp,-v -x c++ - -fsyntax-only < /dev/null 2>&1) \
        <(g++ -Wp,-v -x c++ - -fsyntax-only < /dev/null 2>&1) | grep '^[-+] '

- /boot/system/lib/clang/16/include
+ /boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/13.2.0/include/c++
+ /boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/13.2.0/include/c++/x86_64-unknown-haiku
+ /boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/13.2.0/include/c++/backward
+ /boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/13.2.0/include
+ /boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/13.2.0/include-fixed
- /boot/system/develop/headers/os/arch
```

So, it seems there are five header paths that would need to be added to Clang++ to match the system g++ (and the two extra ones, likely not a problem).

Using a (really gross) `sed` transformation to add these to the Clang include path does allow C++ programs to successfully build with Clang 16.0.6:

```sh
> clang++ -MMD -std=c++20  -Wall -Wextra -Wpedantic -Iinclude -fPIC -O3 -DNDEBUG -D_FORTIFY_SOURCE=2 $(diff -U0 <(clang++ -Wp,-v -x c++ - -fsyntax-only < /dev/null 2>&1) <(g++ -Wp,-v -x c++ - -fsyntax-only < /dev/null 2>&1) | grep '^[+] ' | sed 's/^+ /-I/') -Iinclude -c -o build/obj/tests/tests++.o tests/tests++.cc
> ls -la build/obj/tests/tests++.o
-rw-r--r-- 1 user root 347496 Sep 11 18:02 build/obj/tests/tests++.o
> clang++ build/obj/tests/tests++.o build/obj/tests/tests_shared.o build/lib/libsir_s.a -o tests++ 
> ls -la tests++
-rwxr-xr-x 1 user root 329744 Sep 11 18:04 tests++
> ./tests++
[ ... snip ... ]
done: all 7 tests passed in 0.014sec!
```

The `$(diff -U0 <(clang++ -Wp,-v -x c++ - -fsyntax-only < /dev/null 2>&1) <(g++ -Wp,-v -x c++ - -fsyntax-only < /dev/null 2>&1)` workaround is quite terrible, so perhaps a better solution can be found.

I don't know anything at all about porting or building Clang, so I don't know how difficult it would be to have it find the right paths automatically, or what would happen if this is "fixed" and the GCC version (and thus paths) change again - or if this is even the right solution.

@X547 @davidkaroly @Begasus ?

**Comment by johnsonjh** [comment]
Doing the same comparison for `gcc` vs. `clang` (just C, not C++) shows that `clang` actually has quite a few *more* directories explicitly in the search compared by default, when compared with `gcc`:

```diff
diff -U0 \
    <(clang -Wp,-v -x c - -fsyntax-only < /dev/null 2>&1) \
        <(g -Wp,-v -x c - -fsyntax-only < /dev/null 2>&1) | grep '^[-+] '
- /boot/system/lib/clang/16/include
- /boot/system/develop/headers/os
- /boot/system/develop/headers/os/app
- /boot/system/develop/headers/os/arch
- /boot/system/develop/headers/os/device
- /boot/system/develop/headers/os/drivers
- /boot/system/develop/headers/os/game
- /boot/system/develop/headers/os/interface
- /boot/system/develop/headers/os/kernel
- /boot/system/develop/headers/os/locale
- /boot/system/develop/headers/os/mail
- /boot/system/develop/headers/os/media
- /boot/system/develop/headers/os/midi
- /boot/system/develop/headers/os/midi2
- /boot/system/develop/headers/os/net
- /boot/system/develop/headers/os/opengl
- /boot/system/develop/headers/os/storage
- /boot/system/develop/headers/os/support
- /boot/system/develop/headers/os/translation
- /boot/system/develop/headers/os/add-ons/graphics
- /boot/system/develop/headers/os/add-ons/input_server
- /boot/system/develop/headers/os/add-ons/mail_daemon
- /boot/system/develop/headers/os/add-ons/registrar
- /boot/system/develop/headers/os/add-ons/screen_saver
- /boot/system/develop/headers/os/add-ons/tracker
- /boot/system/develop/headers/os/be_apps/NetPositive
- /boot/system/develop/headers/os/be_apps/Tracker
- /boot/system/develop/headers/bsd
- /boot/system/develop/headers/glibc
- /boot/system/develop/headers/gnu
- /boot/system/develop/headers/posix
- /boot/system/develop/headers
```

**Comment by johnsonjh** [comment]
* Haiku hrev57257

* GCC version 13.2.0 (2023_08_10)

* Clang version 16.0.6:
  ```sh
  > ls -1 /boot/system/packages | grep -E '(clang|llvm)' | grep 16
  llvm16_clang_analysis-16.0.6-3-x86_64.hpkg
  llvm16_clang-16.0.6-3-x86_64.hpkg
  llvm16_libs-16.0.6-3-x86_64.hpkg
  llvm16_libunwind_devel-16.0.6-3-x86_64.hpkg
  llvm16_libunwind-16.0.6-3-x86_64.hpkg
  llvm16_lld-16.0.6-3-x86_64.hpkg
  llvm16-16.0.6-3-x86_64.hpkg
  ```

**Comment by davidkaroly** [comment]
ok this is reproducible with a simple `#include <iostream>`

it seems that the custom implementation for `addLibStdCxxIncludePaths()` is not right, but we can inherit it from the base class `Generic_GCC`

this helps with the following include paths:
```
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/13.2.0/include/c++
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/13.2.0/include/c++/x86_64-unknown-haiku
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/13.2.0/include/c++/backward
```

the remaining two will need some more investigation - these don't really seem C++-specific

```
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/13.2.0/include
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/13.2.0/include-fixed
```

**Comment by johnsonjh** [comment]
@davidkaroly 

The `/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/13.2.0/include-fixed` comes from a GCC script - https://gcc.gnu.org/onlinedocs/gcc/Fixed-Headers.html - which "fixes" incompatible system include files.  Since Haiku's headers are based on glibc and the system compiler is GCC, this directory should always be empty, so it's OK that it isn't included.

The `/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/13.2.0/include` path is also specific to GCC - the corresponding Clang path is `/boot/system/lib/clang/16/include`, so as long as that is included *ahead* of the other paths, then everything should be good!

**Comment by davidkaroly** [comment]
llvm16-16.0.6-4 available in HaikuDepot, this should fix the missing C++ include dirs. Can you retest?

**Comment by johnsonjh** [comment]
@davidkaroly 

It works!  Thanks for the quick fix and I'll close this out as completed.
