### ISSUE TITLE
harfbuzz_devel-7.3.0-1 seems to break pango/gdk development

### ISSUE THREAD

**Issue by kenz-gelsoft** [haikuports/haikuports#8733]
After updating to 7.3.0-1, I start getting errors like following (when re-building firefox):
```
 0:08.85 In file included from /packages/pango-1.50.7-2/.self/develop/headers/pango-1.0/pango/pango-font.h:25,
 0:08.85                  from /packages/pango-1.50.7-2/.self/develop/headers/pango-1.0/pango/pango-attributes.h:25,
 0:08.85                  from /packages/pango-1.50.7-2/.self/develop/headers/pango-1.0/pango/pango.h:25,
 0:08.85                  from /boot/home/src/gecko-dev/obj-ff-dbg/dist/system_wrappers/pango/pango.h:3,
 0:08.85                  from /packages/gtk3-3.24.36-1/.self/develop/headers/gtk-3.0/gdk/gdktypes.h:35,
 0:08.85                  from /packages/gtk3-3.24.36-1/.self/develop/headers/gtk-3.0/gdk/gdkapplaunchcontext.h:30,
 0:08.85                  from /packages/gtk3-3.24.36-1/.self/develop/headers/gtk-3.0/gdk/gdk.h:32,
 0:08.85                  from /boot/home/src/gecko-dev/obj-ff-dbg/dist/system_wrappers/gdk/gdk.h:3,
 0:08.86                  from /boot/home/src/gecko-dev/obj-ff-dbg/dist/include/mozilla/GRefPtr.h:11,
 0:08.86                  from /boot/home/src/gecko-dev/browser/components/shell/nsGNOMEShellService.cpp:26:
 0:08.86 /packages/pango-1.50.7-2/.self/develop/headers/pango-1.0/pango/pango-coverage.h:28:10: fatal error: hb.h: No such file or directory
 0:08.86    28 | #include <hb.h>
 0:08.86       |          ^~~~~~
 0:08.86 compilation terminated.
 0:08.86 /boot/home/src/gecko-dev/config/rules.mk:667: recipe for target 'nsGNOMEShellService.o' failed
```

Restoring to harfbuzz 4.0.0-3 with its deps fixed this.

Pango or GDK will need some update to support 4.0.0 -> 7.3.1 migration?

**Comment by kenz-gelsoft** [comment]
Sorry, just because its build system cached old cflags of prior build.

`pkg-config harfbuzz --cflags` returns correct value, so I had to re-configure my project.

Closing...
