### ISSUE TITLE
Multiple lua installs (5.1/5.2/5.3) conflict with each other

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuports#5564]
Was trying to build freeciv branch S3_0 earlier and had multiple version for lua installed, with haikuporter it isn't a problem as it only takes the one requested (5.3 in this case in the recipe).
But building from Terminal bailed out for building the tolua binary in the src (probably linked against either lua 5.1 or 5.2 library:

```
CC toluabind.o
CCLD tolua
tolua.o: In function `main':
tolua.c:(.text.startup+0x57): undefined reference to `lua_setglobal'
tolua.c:(.text.startup+0x85): undefined reference to `lua_setglobal'
toluabind.o: In function `luaopen_tolua':
toluabind.c:(.text+0x50): undefined reference to `luaL_loadbufferx'
toluabind.c:(.text+0x73): undefined reference to `luaL_loadbufferx'
toluabind.c:(.text+0x96): undefined reference to `luaL_loadbufferx'
toluabind.c:(.text+0xb9): undefined reference to `luaL_loadbufferx'
toluabind.c:(.text+0xdc): undefined reference to `luaL_loadbufferx'
toluabind.o:toluabind.c:(.text+0xff): more undefined references to `luaL_loadbufferx' follow
toluabind.o: In function `luaopen_tolua':
toluabind.c:(.text+0x334): undefined reference to `lua_pcallk'
toluabind.c:(.text+0x34e): undefined reference to `lua_pcallk'
toluabind.c:(.text+0x365): undefined reference to `lua_pcallk'
toluabind.c:(.text+0x37e): undefined reference to `lua_pcallk'
toluabind.c:(.text+0x39e): undefined reference to `lua_pcallk'
toluabind.o:toluabind.c:(.text+0x3be): more undefined references to `lua_pcallk' follow
toluabind.o: In function `tolua_tolua_open':
toluabind.c:(.text+0x5f1): undefined reference to `lua_callk'
../lib/.libs/libtolua.a(tolua_map.o): In function `tolua_push_globals_table':
tolua_map.c:(.text+0x122): undefined reference to `lua_rotate'
../lib/.libs/libtolua.a(tolua_map.o): In function `mapsuper':
tolua_map.c:(.text+0x4d3): undefined reference to `lua_rotate'
../lib/.libs/libtolua.a(tolua_push.o): In function `tolua_pushusertype':
tolua_push.c:(.text+0x19d): undefined reference to `lua_rotate'
tolua_push.c:(.text+0x252): undefined reference to `lua_rotate'
../lib/.libs/libtolua.a(tolua_to.o): In function `tolua_tonumber':
...
```

**Comment by korli** [comment]
The versions should conflict one with another.

**Comment by Begasus** [comment]
There's only **CONFLICTS_devel="** in the recipes, libs don't provide conflicts, that or freeciv should do a cleaner check on lua5.3

**Comment by pulkomandy** [comment]
Because Lua isn't distributed with an official pkg-config file (or at least, older versions weren't, maybe it's better now), applications have to try to detect various versions, and it's not surprising that they would find the wrong libs if they look in $libDir instead of $developLibDir.

Also, it seems Freeciv is compiling its own version of tolua? Can it use a separately packaged one instead? (from http://webserver2.tecgraf.puc-rio.br/~celes/tolua/)

**Comment by Begasus** [comment]
> Can it use a separately packaged one instead?

Had been looking into porting tolua, but seeing it's hardly used by anything else I didn't really investigate, working with the recipe that demands >  5.3 it's ok, ps, this was only for the tolua binary, the lib itself compiled fine

**Comment by Begasus** [comment]
Should be fixed in: https://github.com/haikuports/haikuports/pull/6946
