### ISSUE TITLE
OpenSSH 10.2p1-1 fails with EWOULDBLOCK

### ISSUE THREAD

**Issue by rymdbar** [haikuports/haikuports#13177]
Commit [65909fa][] breaks openssh on Haiku. Oddly not for everyone. Am merely opening this ticket now. Will populate it with details during the day after further debugging.

[65909fa]: https://github.com/openssh/openssh-portable/commit/65909fa

**Comment by korli** [comment]
Which Haiku version?

**Comment by rymdbar** [comment]
To reproduce without openssh, these 37 lines of C should do the same thing: (needs to be linked with `-lnetwork`)

```C
#include <fcntl.h>
#include <netdb.h>
#include <stdio.h>
#include <string.h>

#define IPTOS_DSCP_AF21  0x48
#define IPTOS_DSCP_EF    0xb8

int main() {
    struct addrinfo ai;

    char sa_data[] = { 0x00, 0x16, 0x04, 0xe1, 0x0b, 0xc2, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00 };
    struct sockaddr ai_addr;

    ai.ai_addrlen = 32;
    ai.ai_addr = &ai_addr;
    memcpy(&ai.ai_addr->sa_data, &sa_data, 30);
    ai.ai_addr->sa_family = 1;
    ai.ai_addr->sa_len = 32;
    ai.ai_canonname = "github.com";
    ai.ai_family = AF_INET;
    ai.ai_flags = 2;
    ai.ai_next = NULL;
    ai.ai_protocol = 6;
    ai.ai_socktype = 1;
    int sock = socket(ai.ai_family, ai.ai_socktype, ai.ai_protocol);
    (void)fcntl(sock, F_SETFD, FD_CLOEXEC);
    // int tos = IPTOS_DSCP_AF21;
    int tos = IPTOS_DSCP_EF;
    setsockopt(sock, IPPROTO_IP, IP_TOS, &tos, sizeof(tos));
    int res = connect(sock, ai.ai_addr, ai.ai_addrlen);
    printf("res: %d\n", res);
    perror("errno");
}
```

Expected output:

> res: -1
> errno: Operation would block

Just like from openssh.

**Comment by rymdbar** [comment]
> Which Haiku version?

My impression is to run an up to date system, where `pkgman full-sync` is run frequently. However running `uname -orv` outputs:

1 hrev57937+129 Dec 10 2024 21:49 Haiku

…which is almost a year old. Could that be the entire issue?

**Comment by korli** [comment]
> To reproduce without openssh, these 37 lines of C should do the same thing: (needs to be linked with `-lnetwork`)
...
> Just like from openssh.

If the bug is in the OS, then report at http://dev.haiku-os.org/

**Comment by rymdbar** [comment]
> If the bug is in the OS, then report at http://dev.haiku-os.org/

That's the plan. I applied for a trac account an hour or a few before opening this issue here, but am still waiting for the email with the activation link.

**Comment by korli** [comment]
> That's the plan. I applied for a trac account an hour or a few before opening this issue here, but am still waiting for the email with the activation link.

@humdingerb @waddlesplash please check the trac user sampi.

Thanks for the testcase. I'll check it soon.

**Comment by korli** [comment]
I tried the testcase on a current nightly in a VM, connect() succeeds. I'll test on a r1beta5 next.
EDIT: also succeeds on r1beta5

**Comment by humdingerb** [comment]
No idea if it's the same issue, but connecting via ssh to my LibreElec running mediaplayer, the connection stalls after a few seconds. Just doesn't take any keyboard input... Works again after downgrading to openssh-10.0p1-2. This is hrev59114, 64bit.

**Comment by korli** [comment]
> No idea if it's the same issue, but connecting via ssh to my LibreElec running mediaplayer, the connection stalls after a few seconds. Just doesn't take any keyboard input... Works again after downgrading to openssh-10.0p1-2. This is hrev59114, 64bit.

using tcpdump/wireshark might help to diagnose the problem.

**Comment by humdingerb** [comment]
There's a lot of output generated quite quickly with "tcpdump". I'm also completely unfamiliar with that tool, so I'm not sure this helps.

Typical output with the working openssh-10.0p1-2-x86_64.hpkg:

```
16:58:11.707031 IP shredder.fritz.box.40143 > kodi-n100.ssh: Flags [P.], seq 13664:13700, ack 13841, win 255, options [nop,nop,TS val 316827 ecr 2232284767], length 36
16:58:11.709125 IP kodi-n100.ssh > shredder.fritz.box.40143: Flags [P.], seq 13841:13877, ack 13700, win 63, options [nop,nop,TS val 2232284787 ecr 316827], length 36
16:58:11.728228 IP shredder.fritz.box.40143 > kodi-n100.ssh: Flags [P.], seq 13700:13736, ack 13877, win 255, options [nop,nop,TS val 316848 ecr 2232284787], length 36
16:58:11.730226 IP kodi-n100.ssh > shredder.fritz.box.40143: Flags [P.], seq 13877:13913, ack 13736, win 63, options [nop,nop,TS val 2232284808 ecr 316848], length 36
```

Compared to the new openssh-10.2p1-1-x86_64.hpkg:

```
16:55:37.960655 IP shredder.fritz.box.40026 > kodi-n100.ssh: Flags [P.], seq 3383:3523, ack 3051, win 255, options [nop,nop,TS val 163043 ecr 2232131001], length 140
16:55:37.960683 IP kodi-n100.ssh > shredder.fritz.box.40026: Flags [P.], seq 3051:3151, ack 3523, win 76, options [nop,nop,TS val 2232131004 ecr 163043], length 100
16:55:37.960714 IP shredder.fritz.box.40026 > kodi-n100.ssh: Flags [P.], seq 3523:3831, ack 3151, win 255, options [nop,nop,TS val 163047 ecr 2232131004], length 308
16:55:37.960741 IP kodi-n100.ssh > shredder.fritz.box.40026: Flags [P.], seq 3151:3179, ack 3831, win 79, options [nop,nop,TS val 2232131020 ecr 163047], length 28
16:55:37.960768 IP shredder.fritz.box.40026 > kodi-n100.ssh: Flags [P.], seq 3831:3943, ack 3179, win 255, options [nop,nop,TS val 163062 ecr 2232131020], length 112
16:55:37.960795 IP kodi-n100.ssh > shredder.fritz.box.40026: Flags [P.], seq 3179:3947, ack 3943, win 79, options [nop,nop,TS val 2232131023 ecr 163062], length 768
```

**Comment by pulkomandy** [comment]
Use it with the -w option to create a pcap file. Have it running in the background while you reproduce the issue. Then send us the resulting file (privately, as it will contain all your network traffic) which can be analyzed with wireshark.
If you have a capture with the working version, you can also include that.

The text output only shows the headers of each packet, but the pcap file will also incldue the entire contents, which will likely be useful in this case? (unless what you shared is enough for someone to see the issue already).


7 novembre 2025 à 17:16 "humdinger" ***@***.*** ***@***.***?to=%22humdinger%22%20%3Cnotifications%40github.com%3E > a écrit:

**Comment by humdingerb** [comment]
Unfortunately, with the non-working openssh package the resulting pcap file is only 24 bytes when the Terminal prompt freezes and it appears empty when opening with wireshark.

**Comment by rymdbar** [comment]
> If the bug is in the OS, then report at http://dev.haiku-os.org/

Trac ticket [#10817](https://dev.haiku-os.org/ticket/19817) has been filed.

**Comment by rymdbar** [comment]
> I tried the testcase on a current nightly in a VM, connect() succeeds […] also succeeds on r1beta5

It seems I was a bit sloppy with not informing that something unknown needs to happen to put the computer in the faulty state. Everything works for me after a fresh boot, and rebooting does make the issue go away for a while. Apologies for forgetting this crucial time and wasting your time!

**Comment by rymdbar** [comment]
> No idea if it's the same issue, but connecting via ssh to my LibreElec running mediaplayer, the connection stalls after a few seconds. Just doesn't take any keyboard input... Works again after downgrading to openssh-10.0p1-2. This is hrev59114, 64bit.

If still able to reproduce the problem, would you be able to try the code snippet in [comment 3](https://github.com/haikuports/haikuports/issues/13177#issuecomment-3478450495) please?

It could also be interesting if you could run:

```sh
touch /tmp/_
/bin/strace /bin/ssh -F /tmp/_ -v _@github.com >/tmp/out.log 2>/tmp/err.log
```

Compare the resulting files with what I posted at [haiku+openssh10.2p1-1](https://www.netizen.se/docs/haiku+openssh10.2p1-1) and post whether it looks similar to you. Whether you too get the 4000 lines I excluded there is really the question.

**Comment by humdingerb** [comment]
> If still able to reproduce the problem, would you be able to try the code snippet in https://github.com/haikuports/haikuports/issues/13177#issuecomment-3478450495 please?

I had to compile with "-Wno-narrowing" BTW. With both openssh  versions I get:

```
res: 0
errno: Illegal byte sequence
```

When trying this:

```
touch /tmp/_
/bin/strace /bin/ssh -F /tmp/_ -v _@github.com >/tmp/out.log 2>/tmp/err.log
```

the results look pretty similar. If those logs are save to upload (I temporarily removed the ~/config/settings/ssh folder) I can upload them somewhere. I also get many entries like `[ 14632] close(0x8f) = 0x80006000 Bad file descriptor (1 us)` . The logs are about 1450 lines long.

**Comment by rymdbar** [comment]
Thanks for this input!

> > If still able to reproduce the problem […]

Given how I initially left out crucial information and thus was unclear, it might be a good idea to double confirm that you're still actually experiencing the issue connecting to your LibreElec? (For me the issue disappears for a while on reboot.)

> I had to compile with "-Wno-narrowing" BTW. With both openssh versions I get:

Lets assume the [no-narrowing][] warning is unimportant for now. Do I understand things correctly if guessing it happens on the line assigning the constant to `tos`?

[no-narrowing]: https://gcc.gnu.org/onlinedocs/gcc/C_002b_002b-Dialect-Options.html#index-Wnarrowing

> ```
> res: 0
> errno: Illegal byte sequence
> ```

These are both successes. The interesting part is _res = 0_. The value of errno is only relevant when _res ≠ 0_.

> When trying […] the results look pretty similar. If those logs are save to upload (I temporarily removed the ~/config/settings/ssh folder) I can upload them somewhere.

I would believe they should be safe, but would hate it if I was mistaken. If making sure no ssh-agent is running and having an empty config I can't see how they would expose anything sensitive. Unless you're confident, please to not post them in public. One thing I believe you could do is create a new note on my HedgeDoc. It would technically still be public, but unless making the link public I would be surprised if anyone but me would be able to find it.

> I also get many entries like `[ 14632] close(0x8f) = 0x80006000 Bad file descriptor (1 us)` . The logs are about 1450 lines long.

That's significantly less than 4096 and 1450-0x8f is 1307 which is not precisely close to 2ⁿ for any n. Thats 1450 lines for all of the logs though? Not just the chunk of _Bad file descriptor_ lines?

**Comment by humdingerb** [comment]
> you're still actually experiencing the issue connecting to your LibreElec?

Yep. Totally reproducible the ssh connection freezes after a second with openssh-10.2p1; works with openssh-10.0p1.

> ets assume the [no-narrowing](https://gcc.gnu.org/onlinedocs/gcc/C_002b_002b-Dialect-Options.html#index-Wnarrowing) warning is unimportant for now. Do I understand things correctly if guessing it happens on the line assigning the constant to tos?

Close, no cigar. :) These are the specific lines:

```
test.cpp:12:42: error: narrowing conversion of '225' from 'int' to 'char' [-Wnarrowing]
   12 |     char sa_data[] = { 0x00, 0x16, 0x04, 0xe1, 0x0b, 0xc2, 0x00, 0x00,
      |                                          ^~~~
test.cpp:12:54: error: narrowing conversion of '194' from 'int' to 'char' [-Wnarrowing]
   12 |     char sa_data[] = { 0x00, 0x16, 0x04, 0xe1, 0x0b, 0xc2, 0x00, 0x00,
      |                                                      ^~~~
test.cpp:23:23: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
   23 |     ai.ai_canonname = "github.com";
```

> Thats 1450 lines for all of the logs though? Not just the chunk of Bad file descriptor lines?
Yep, the complete logs.

> Unless you're confident, please to not post them in public. One thing I believe you could do is create a new note on my HedgeDoc.

Since I'm unfamiliar with HedgeDoc and where to find you there - and since I've checked the logs once and replaced the only key inthere with "[REDACTED]" - I've temporarily uploaded it to https://app-share.mailbox.org/appsuite/api/share/08c0c5f40650504b8833e15650504c96a7d4dbd641663a26/1/8/MzQ/MzQvODY0.

**Comment by rymdbar** [comment]
> Close, no cigar. :) These are the specific lines:

Ah! I guess those ought to be `unsigned char` for the warnings to go away, but I'd be more than surprised if it actually matters for our problems.

> Since I'm unfamiliar with HedgeDoc

HedgeDoc is the name of the software where I published my previously linked notes, but your method with using mailbox.org worked at least as good!

Looking at the logs I feel embarrassed to not have compared my own logs with those of a working run. Running out of file descriptors is apparently "normal" and thus completely unrelated to what we're looking for.

If searching the collected strace logs for `connect()`:s. We see three occurences each in all of the out logs, where the first two are on port 53 and thus DNS-related. Looking at the third, we see:

Mine, 10.2p1-1:
> [ 43585] connect(0x3, {AF_INET, 4.225.11.194/22}, 0x20) = 0x8000000b Operation would block (75000121 us)

Yours, 10.0p2
> [ 14632] connect(0x3, {AF_INET, 140.82.121.4/22}, 0x20) = 0x0 No error (36749 us)

Yours, 10.2p1
> [ 14533] connect(0x3, {AF_INET, 140.82.121.3/22}, 0x20) = 0x0 No error (36847 us)

In other words, yours appear to be a different error. If that's the case, I suggest opening a separate issue for it, to not conflate disjunct matters. Please feel free to tag me in it. Did you try running ssh with triple verbosity (`-vvv`)? The output of doing so might be a good start of a new issue?

**Comment by korli** [comment]
Interesting comment in https://github.com/openssh/openssh-portable/commit/289239046b2c4b0076c14394ae9703a879e78706

> This is important now that the default interactive IPQoS is EF
> (Expedited Forwarding), as many networks are configured to allow
> only relatively small amounts of traffic of this class and they will
> aggressively deprioritise the entire connection if this is exceeded.

Might be an idea to check the traffic class before the problem appears.

**Comment by korli** [comment]
Please check with `ssh -o IPQoS=none` whether the problem disappears.

**Comment by humdingerb** [comment]
> ssh -o IPQoS=none

Give the man a cigar! With that option it all works perfectly also with openssh-10.2p1-1, no stalls.
Thanks very much!
Should this option be the default?

**Comment by korli** [comment]
> > ssh -o IPQoS=none
> 
> Give the man a cigar! With that option it all works perfectly also with openssh-10.2p1-1, no stalls. Thanks very much! Should this option be the default?

Dunno. See for instance how it can be added in the ssh config: https://superuser.com/questions/1816580/why-does-it-seem-that-ssh-is-mysteriously-blocked

Does openssl 10.2 on another OS exhibit the issue on your local network?

**Comment by humdingerb** [comment]
I have some Linux Mint here (no idea what version, or how to find out...).
openssl version says:
> OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)

ssh into my Kodi player works without the IPQoS option.

**Comment by korli** [comment]
> I have some Linux Mint here (no idea what version, or how to find out...). openssl version says:
> 
> > OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)
> 
> ssh into my Kodi player works without the IPQoS option.

Sorry I meant openssh version.

**Comment by humdingerb** [comment]
```
humdinger@SchenkerB513:~$ ssh -V
OpenSSH_8.9p1 Ubuntu-3ubuntu0.13, OpenSSL 3.0.2 15 Mar 2022
```
how ever that translate to our 10.2p1...

**Comment by rymdbar** [comment]
> Please check with `ssh -o IPQoS=none` whether the problem disappears.

Yes adding that flag both makes connections succeed when the network stack is in the failed state and prevents the state to occur. Quite unsurprising since [65909fa](https://github.com/openssh/openssh-portable/commit/65909fa) essentially is a single line change switching tos from `IPTOS_DSCP_AF21` to `IPTOS_DSCP_EF`, but good to verify never the less.

**Comment by rymdbar** [comment]
> Does openss<s>l</s>h 10.2 on another OS exhibit the issue on your local network?

On my OpenBSD laptop I've been running ssh 10.2 since October 22:th, the very day 7.8 was released. I'm also using openssh-portable 10.2p1 on Artix Linux. Not sure exactly when I upgraded there, but both of these machines see a lot more usage than my Sunday only Haiku system. 

The QoS policies of some networks are the trigger, but the fault lies in how Haiku's network stack gets stuck in a faulty state. Logging in to a VPS on linode/akkamai appears to be the easiest way to reproduce.

Will try collecting some pcaps and attempt analyzing them, but am reluctant to post such raw data in public.

**Comment by Begasus** [comment]
PR https://github.com/haikuports/haikuports/pull/13178 is up for this, status?

**Comment by korli** [comment]
Seems like https://marc.info/?l=openssh-unix-dev&m=177049276118256&w=2 
Recommended is to update the router firmware when possible.
