### PR TITLE
update 0.a.d

### PR DESCRIPTION
**Pull request by pulkomandy**
When submitting changes to Haikuports, please check the following:

- [x] You are not a robot.
- [ ] The modified recipe was confirmed to build on your Haiku machine.
- [ ] The license and copyright information in modified recipes are correct.
- [ ] The recipe follows one of the templates from https://github.com/haikuports/haikuporter/tree/master/generic (in particular, the fields are in the right [order](https://github.com/haikuports/haikuports/wiki/HaikuPorter-Guidelines#ordering)).
- [ ] The recipe is in the right category (matching Gentoo's overlays if the recipe is available there for example, use https://gpo.zugaina.org to search for existing recipes in Gentoo).

See the [guidelines](https://github.com/haikuports/haikuports/wiki/HaikuPorter-Guidelines) for more details.

### CODE REVIEW

**Comment by pulkomandy** [comment]
Trying to build spidermonkey hits a regression in Python packaging:

```
 0:00.72 Using Python 3.14.6 from /boot/home/.mozbuild/srcdirs/mozjs-128.13.0-5b4974bab5b7/_virtualenvs/build/non-packaged/bin/python
 0:00.73 Traceback (most recent call last):
 0:00.73   File "/sources/mozjs-128.13.0/configure.py", line 351, in <module>
 0:00.73     sys.exit(main(sys.argv))
 0:00.73              ~~~~^^^^^^^^^^
 0:00.73   File "/sources/mozjs-128.13.0/configure.py", line 125, in main
 0:00.73     _activate_build_virtualenv()
 0:00.73     ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
 0:00.73   File "/sources/mozjs-128.13.0/configure.py", line 345, in _activate_build_virtualenv
 0:00.73     if not build_site.ensure():
 0:00.73            ~~~~~~~~~~~~~~~~~^^
 0:00.73   File "/sources/mozjs-128.13.0/python/mach/mach/site.py", line 575, in ensure
 0:00.73     _create_venv_with_pthfile(
 0:00.73     ~~~~~~~~~~~~~~~~~~~~~~~~~^
 0:00.73         self._virtualenv,
 0:00.73         ^^^^^^^^^^^^^^^^^
 0:00.73     ...<3 lines>...
 0:00.73         self._metadata,
 0:00.73         ^^^^^^^^^^^^^^^
 0:00.73     )
 0:00.73     ^
 0:00.73   File "/sources/mozjs-128.13.0/python/mach/mach/site.py", line 1322, in _create_venv_with_pthfile
 0:00.73     process = subprocess.run(
 0:00.73         [sys.executable, "-m", "venv", "--without-pip", virtualenv_root],
 0:00.73     ...<2 lines>...
 0:00.73         encoding="UTF-8",
 0:00.73     )
 0:00.74   File "/packages/python3.14-3.14.6-2/.self/lib/python3.14/subprocess.py", line 555, in run
 0:00.74     with Popen(*popenargs, **kwargs) as process:
 0:00.74          ~~~~~^^^^^^^^^^^^^^^^^^^^^^
 0:00.74   File "/packages/python3.14-3.14.6-2/.self/lib/python3.14/subprocess.py", line 1039, in __init__
 0:00.74     self._execute_child(args, executable, preexec_fn, close_fds,
 0:00.74     ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 0:00.74                         pass_fds, cwd, env,
 0:00.74                         ^^^^^^^^^^^^^^^^^^^
 0:00.74     ...<5 lines>...
 0:00.74                         gid, gids, uid, umask,
 0:00.74                         ^^^^^^^^^^^^^^^^^^^^^^
 0:00.74                         start_new_session, process_group)
 0:00.74                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 0:00.74   File "/packages/python3.14-3.14.6-2/.self/lib/python3.14/subprocess.py", line 1992, in _execute_child
 0:00.74     raise child_exception_type(errno_num, err_msg, err_filename)
 0:00.74 FileNotFoundError: [Errno -2147459069] No such file or directory: '/boot/home/.mozbuild/srcdirs/mozjs-128.13.0-5b4974bab5b7/_virtualenvs/build/non-packaged/bin/python'
```

With python 3.10 it fails to find mozfile.

This is pretty early on in the build, so it should be easy to test.

**Comment by OscarL** [comment]
SpiderMonkey issue is another case of #14503 :-/ (will try to have that fixed this weekend).

Will probably merge the `mozfile` recipe after I make some tweaks to it tonight. Thanks!

**Comment by pulkomandy** [comment]
mozfile, premake and spidermonkey are building fine.

Now 0ad is failing building built-in dependencies: fcollada and nvtt. Patching these is a bit inconvenient because they are provided as archives that are extracted and patched by 0ad buildsystem.

Writing a separate recipe for nvtt may be a good idea.

**Comment by pulkomandy** [comment]
Current status:

- All dependencies are building
- Main code is building
- Linker errors:
  - Something is linking to icu73 instead of icu74. Probably a dependency needs to be rebuilt
  - Cannot link libnetwork because there is an internal library in the build also called libnetwork
  - Some other undefined references due to missing Haiku code for some things. Some of the needed functions can be retrieved from the older 0.23 patchset, others will need to be written.

**Comment by pulkomandy** [comment]
Asked for help on 0ad side: https://gitea.wildfiregames.com/0ad/0ad/issues/9109

**Comment by Begasus** [comment]
Linking with -lnetwork seemed to work with the upstream patch, but building the object psnetwork doesn't seem to work?
```
make[1]: *** No rule to make target '../../../source/pch/psnetwork/precompiled.h', needed by 'obj/psnetwork_Release/precompiled.h.gch'.  Stop.
```
Can't comment upstream without creating an account there, so here it is so far. :)

**Comment by Begasus** [comment]
Got a bit further with:
```diff
diff --git a/build/premake/premake5.lua b/build/premake/premake5.lua
index 5c0c5da..29e2a98 100644
--- a/build/premake/premake5.lua
+++ b/build/premake/premake5.lua
@@ -720,7 +720,8 @@ function setup_all_libs ()
 	if not _OPTIONS["without-miniupnpc"] then
 		table.insert(extern_libs, "miniupnpc")
 	end
-	setup_static_lib_project("network", source_dirs, extern_libs, {})
+	setup_static_lib_project("psnetwork", source_dirs, extern_libs, {})
+	includedirs { source_root .. "/pch/psnetwork" }
 
 	source_dirs = {
 		"rlinterface",
diff --git a/source/pch/network/precompiled.cpp b/source/pch/psnetwork/precompiled.cpp
similarity index 100%
rename from source/pch/network/precompiled.cpp
rename to source/pch/psnetwork/precompiled.cpp
diff --git a/source/pch/network/precompiled.h b/source/pch/psnetwork/precompiled.h
similarity index 100%
rename from source/pch/network/precompiled.h
rename to source/pch/psnetwork/precompiled.h
```
But got other linking errors then:
```
==== Building pyrogenesis (release) ====
Creating obj/pyrogenesis_Release
main.cpp
Linking pyrogenesis
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/13.3.0/../../../../x86_64-unknown-haiku/bin/ld: ../../../binaries/system/libpsnetwork.a(NetSession.o): in function `CNetClientSession::RunNetLoop(CNetClientSession*)':
/sources/0ad-0.28.0/build/workspaces/gcc/../../../source/network/NetSession.cpp:100:(.text+0x669): undefined reference to `debug_SetThreadName(char const*)'
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/13.3.0/../../../../x86_64-unknown-haiku/bin/ld: ../../../binaries/system/libpsnetwork.a(NetServer.o): in function `CNetServerWorker::SetupUPnP(unsigned short)':
/sources/0ad-0.28.0/build/workspaces/gcc/../../../source/network/NetServer.cpp:222:(.text+0xc98): undefined reference to `debug_SetThreadName(char const*)'
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/13.3.0/../../../../x86_64-unknown-haiku/bin/ld: ../../../binaries/system/libpsnetwork.a(NetServer.o): in function `CNetServerWorker::RunThread(CNetServerWorker*)':
/sources/0ad-0.28.0/build/workspaces/gcc/../../../source/network/NetServer.cpp:407:(.text+0x1bb9): undefined reference to `debug_SetThreadName(char const*)'
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/13.3.0/../../../../x86_64-unknown-haiku/bin/ld: ../../../binaries/system/libengine.a(Filesystem.o): in function `ReloadChangedFiles()':
/sources/0ad-0.28.0/build/workspaces/gcc/../../../source/ps/Filesystem.cpp:87:(.text+0x308): undefined reference to `dir_watch_Poll(std::vector<DirWatchNotification, std::allocator<DirWatchNotification> >&)'
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/13.3.0/../../../../x86_64-unknown-haiku/bin/ld: ../../../binaries/system/libengine.a(GameSetup.o): in function `EarlyInit()':
/sources/0ad-0.28.0/build/workspaces/gcc/../../../source/ps/GameSetup/GameSetup.cpp:503:(.text+0x1c45): undefined reference to `debug_SetThreadName(char const*)'
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/13.3.0/../../../../x86_64-unknown-haiku/bin/ld: ../../../binaries/system/libengine.a(Paths.o): in function `Paths::Root(Path const&)':
/sources/0ad-0.28.0/build/workspaces/gcc/../../../source/ps/GameSetup/Paths.cpp:176:(.text+0xfe7): undefined reference to `sys_ExecutablePathname()'
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/13.3.0/../../../../x86_64-unknown-haiku/bin/ld: ../../../binaries/system/libengine.a(SoundManager.o): in function `CSoundManagerWorker::RunThread(CSoundManagerWorker*)':
/sources/0ad-0.28.0/build/workspaces/gcc/../../../source/soundmanager/SoundManager.cpp:121:(.text._ZN19CSoundManagerWorker9RunThreadEPS_[_ZN19CSoundManagerWorker9RunThreadEPS_]+0x18): undefined reference to `debug_SetThreadName(char const*)'
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/13.3.0/../../../../x86_64-unknown-haiku/bin/ld: ../../../binaries/system/libengine.a(TaskManager.o): in function `Threading::WorkerThread::RunUntilDeath()':
/sources/0ad-0.28.0/build/workspaces/gcc/../../../source/ps/TaskManager.cpp:253:(.text+0x54f): undefined reference to `debug_SetThreadName(char const*)'
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/13.3.0/../../../../x86_64-unknown-haiku/bin/ld: ../../../binaries/system/libengine.a(UserReport.o): in function `CUserReporterWorker::RunThread(CUserReporterWorker*)':
/sources/0ad-0.28.0/build/workspaces/gcc/../../../source/ps/UserReport.cpp:243:(.text._ZN19CUserReporterWorker9RunThreadEPS_[_ZN19CUserReporterWorker9RunThreadEPS_]+0x18): undefined reference to `debug_SetThreadName(char const*)'
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/13.3.0/../../../../x86_64-unknown-haiku/bin/ld: ../../../binaries/system/liblowlevel.a(app_hooks.o): in function `def_get_log_dir()':
/sources/0ad-0.28.0/build/workspaces/gcc/../../../source/lib/app_hooks.cpp:40:(.text+0xab): undefined reference to `sys_ExecutablePathname()'
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/13.3.0/../../../../x86_64-unknown-haiku/bin/ld: ../../../binaries/system/liblowlevel.a(debug.o): in function `debug_BuildErrorMessage(wchar_t const*, wchar_t const*, int, char const*, void*, wchar_t const*)':
/sources/0ad-0.28.0/build/workspaces/gcc/../../../source/lib/debug.cpp:298:(.text+0x6cf): undefined reference to `debug_DumpStack(wchar_t*, unsigned long, void*, wchar_t const*)'
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/13.3.0/../../../../x86_64-unknown-haiku/bin/ld: ../../../binaries/system/liblowlevel.a(real_directory.o): in function `RealDirectory::Watch()':
/sources/0ad-0.28.0/build/workspaces/gcc/../../../source/lib/file/common/real_directory.cpp:66:(.text+0x32e): undefined reference to `dir_watch_Add(Path const&, std::shared_ptr<DirWatch>&)'
collect2: error: ld returned 1 exit status
```

EDIT: maybe missing linking with "libpsnetwork.a"?

**Comment by pulkomandy** [comment]
The remaining "undefined reference" errors are because some Haiku specific code needs to be added for these. I'll see if I can extract the needed code from the 0.0.23 patch, or if I need to write some new functions from scratch.

Nice to see that the other errors are fixed and only that remains!

**Comment by Begasus** [comment]
Template for pkg-config file for spidermonkey (feel free to adjust where needed), should go into INSTALL().
Checked with 0ad, no more warnings that mozjs-128 isn't found, so does pick it up.
```
# Add pkgconfig file
mkdir -p $developLibDir/pkgconfig
cat > $developLibDir/pkgconfig/mozjs-128.pc << EOF
bindir=$prefix/bin
exec_prefix=$prefix
libdir=$libDir
includedir=$includeDir

Name: mozjs-128
Description: $SUMMARY
Version: $portVersion
Libs: -L$developLibDir -lmozjs-128
Cflags: -I$includeDir
EOF
```

**Comment by pulkomandy** [comment]
I think it's good to go now, but for some reason I am still getting undefined references to icu73. I don't understand where that comes from.

Maybe you can try on your side.

**Comment by Begasus** [comment]
I used ICU73 for this, changed this in the recipe

**Comment by Peppersawce** [comment]
I can confirm it builds with icu73 (and doesn't with icu74), I can also confirm it builds with boost 1.88, as I had that one installed already and didn't want to downgrade its dev libraries.

I do hit policy errors at the end with the current recipe, however:
```
Warning: POLICY ERROR: "/packaging/0ad/apps/0ad/pyrogenesis" needs library "libfmt.so.11", but the package doesn't seem to declare that as a requirement
Warning: POLICY ERROR: "/packaging/0ad/apps/0ad/pyrogenesis" needs library "libcrypto.so.3", but the package doesn't seem to declare that as a requirement
Warning: POLICY ERROR: "/packaging/0ad/apps/0ad/pyrogenesis" needs library "libssl.so.3", but the package doesn't seem to declare that as a requirement
Warning: POLICY ERROR: "/packaging/0ad/apps/0ad/pyrogenesis" needs library "libmozjs-128.so", but the package doesn't seem to declare that as a requirement
Warning: POLICY ERROR: "/packaging/0ad/apps/0ad/pyrogenesis" needs library "libfreetype.so.6", but the package doesn't seem to declare that as a requirement
Warning: POLICY ERROR: requires "lib:libgl" doesn't seem to be used
Warning: POLICY ERROR: requires "lib:libboost_system" doesn't seem to be used
Warning: POLICY ERROR: requires "lib:libnspr4" doesn't seem to be used
Warning: POLICY ERROR: requires "lib:libboost_filesystem" doesn't seem to be used
Warning: POLICY ERROR: requires "lib:libplds4" doesn't seem to be used
Warning: POLICY ERROR: requires "lib:libplc4" doesn't seem to be used
```

I'll be patching the recipe locally for this and then try to get the data recipe up to date as well.

EDIT:
0ad_data-0.28.0.recipe
```
SUMMARY="O A.D. - Game Data"
DESCRIPTION="Data for the game 0 A.D."
HOMEPAGE="https://play0ad.com/"
COPYRIGHT="Wildfire Games"
LICENSE="0ADLicense"
REVISION="1"
SOURCE_URI="https://releases.wildfiregames.com/0ad-$portVersion-unix-data.tar.xz"
CHECKSUM_SHA256="e844b30ae2102c47e0a4fff2f0e0ef05ba0cebb1890aa72276fa12457c39526f"
SOURCE_DIR="0ad-$portVersion"

ARCHITECTURES="any"

DISABLE_SOURCE_PACKAGE="yes"

PROVIDES="
	0ad_data = $portVersion
	"

INSTALL()
{
	mkdir -p $dataDir/0ad
	cp -R binaries/data/* $dataDir/0ad
}
```
EDIT2: The binary complains about missing (internal?) libraries:
nverror
EDIT3: I copied the libraries from 0ad's app folder to `/boot/home/config/non-packaged/lib`, now I get this error:
>/boot/system/apps/0ad> pyrogenesis 
runtime_loader: /boot/home/config/non-packaged/lib/libnvcore.so: Could not resolve symbol 'backtrace_symbols'
resolve symbol "backtrace_symbols" returned: -2147478780
runtime_loader: /boot/home/config/non-packaged/lib/libnvcore.so: Troubles relocating: Symbol not found

**Comment by Begasus** [comment]
Progress? :) (nuke libexecinfo in BUILD_REQUIRES)
```
/boot/system/apps/0ad> pyrogenesis 
********************************************************
WARNING: Attempted to run the game with root permission!
This is not allowed because it can alter home directory 
permissions and opens your system to vulnerabilities.   
(You received this message because you were either      
  logged in as root or used e.g. the 'sudo' command.)    
********************************************************
```
EDIT: patch for root
```diff
diff --git a/source/main.cpp b/source/main.cpp
index 0ad09c1..bc1e2ab 100644
--- a/source/main.cpp
+++ b/source/main.cpp
@@ -805,7 +805,7 @@ extern "C" __attribute__((visibility ("default"))) int pyrogenesis_main(int argc
 int main(int argc, char* argv[])
 #endif
 {
-#if OS_UNIX
+#if OS_UNIX && !OS_HAIKU
 	// Don't allow people to run the game with root permissions,
 	//	because bad things can happen, check before we do anything
 	if (geteuid() == 0)
```

And then:

0ad

**Comment by Begasus** [comment]
Current recipe here (with cleanups):
```
SUMMARY="O A.D. - Game"
DESCRIPTION="A free, open-source, Real-Time Strategy (RTS) game."
HOMEPAGE="https://play0ad.com/"
COPYRIGHT="Wildfire Games"
LICENSE="0ADLicense"
REVISION="1"
SOURCE_URI="https://releases.wildfiregames.com/0ad-$portVersion-unix-build.tar.xz"
CHECKSUM_SHA256="27e217755ef76a922fe58dbf593d96e54b6ed2375d23f548c35619aa6bd5a42a"
SOURCE_DIR="0ad-$portVersion"
PATCHES="0ad-$portVersion.patchset"
ADDITIONAL_FILES="0ad.rdef.in"

ARCHITECTURES="all !x86_gcc2"
SECONDARY_ARCHITECTURES="x86"

PROVIDES="
	0ad$secondaryArchSuffix = $portVersion
	app:0ad$secondaryArchSuffix = $portVersion
	lib:libcollada$secondaryArchSuffix
	lib:libnvcore$secondaryArchSuffix
	lib:libnvimage$secondaryArchSuffix
	lib:libnvmath$secondaryArchSuffix
	lib:libnvtt$secondaryArchSuffix
	"
REQUIRES="
	haiku$secondaryArchSuffix
	lib:libcrypto$secondaryArchSuffix
	lib:libcurl$secondaryArchSuffix
	lib:libenet$secondaryArchSuffix
	lib:libfmt$secondaryArchSuffix
	lib:libfreetype$secondaryArchSuffix
	lib:libgloox$secondaryArchSuffix
	lib:libiconv$secondaryArchSuffix
	lib:libicui18n$secondaryArchSuffix
	lib:libicuuc$secondaryArchSuffix
	lib:libminiupnpc$secondaryArchSuffix
	lib:libmozjs_128$secondaryArchSuffix
	lib:libopenal$secondaryArchSuffix
	lib:libpng16$secondaryArchSuffix
	lib:libSDL2_2.0$secondaryArchSuffix
	lib:libsodium$secondaryArchSuffix
	lib:libssl$secondaryArchSuffix
	lib:libvorbisfile$secondaryArchSuffix
	lib:libxml2$secondaryArchSuffix
	lib:libz$secondaryArchSuffix
	0ad_data == $portVersion
	"


BUILD_REQUIRES="
	haiku${secondaryArchSuffix}_devel
	devel:libboost_system$secondaryArchSuffix >= 1.83.0
	devel:libcrypto$secondaryArchSuffix
	devel:libcurl$secondaryArchSuffix
	devel:libenet$secondaryArchSuffix
	devel:libfmt$secondaryArchSuffix >= 11
	devel:libfreetype$secondaryArchSuffix
	devel:libgloox$secondaryArchSuffix
	devel:libicui18n$secondaryArchSuffix >= 73
	devel:libicuuc$secondaryArchSuffix >= 73
	devel:libiconv$secondaryArchSuffix
	devel:libminiupnpc$secondaryArchSuffix
	devel:libmozjs_128$secondaryArchSuffix
	devel:libopenal$secondaryArchSuffix
	devel:libpng16$secondaryArchSuffix
	devel:libSDL2_2.0$secondaryArchSuffix
	devel:libsodium$secondaryArchSuffix
	devel:libssl$secondaryArchSuffix
	devel:libvorbis$secondaryArchSuffix
	devel:libxml2$secondaryArchSuffix
	"

BUILD_PREREQUIRES="
	cmd:awk
	cmd:cmake
	cmd:gcc$secondaryArchSuffix
	cmd:g++$secondaryArchSuffix
	cmd:ld$secondaryArchSuffix
	cmd:make
	cmd:patch
	cmd:perl
	cmd:pkg_config$secondaryArchSuffix
	cmd:premake5
	cmd:python3.14
	cmd:sed
	cmd:which
	cmd:xargs
	"

BUILD()
{
	mkdir -p source/pch/psnetwork
	cp source/pch/network/precompiled.{h,cpp} source/pch/psnetwork/

	./libraries/build-source-libs.sh --with-system-premake --with-system-mozjs \
		$jobArgs
	cd build/workspaces
	./update-workspaces.sh --without-tests --without-atlas --minimal-flags \
		--with-system-premake5 --with-system-mozjs --datadir=$dataDir/0ad $jobArgs

	cd gcc
	make $jobArgs
}

INSTALL()
{
	mkdir -p $appsDir/0ad $dataDir/0ad $libDir

	cp -R binaries/data/* $dataDir/0ad
	cp -R binaries/system/*.so $libDir
	cp -R binaries/system/pyrogenesis $appsDir/0ad

	local APP_SIGNATURE="application/x-vnd.pyrogenesis-0ad"
	local MAJOR="`echo "$portVersion" | cut -d. -f1`"
	local MIDDLE="`echo "$portVersion" | cut -d. -f2`"
	local MINOR="`echo "$portVersion" | cut -d. -f3 | cut -db -f1`"
	local LONG_INFO="$SUMMARY"
	sed \
		-e "s|@APP_SIGNATURE@|$APP_SIGNATURE|" \
		-e "s|@MAJOR@|$MAJOR|" \
		-e "s|@MIDDLE@|$MIDDLE|" \
		-e "s|@MINOR@|$MINOR|" \
		-e "s|@LONG_INFO@|$LONG_INFO|" \
		$portDir/additional-files/0ad.rdef.in > $sourceDir/build/0ad.rdef

	addResourcesToBinaries $sourceDir/build/0ad.rdef $appsDir/0ad/pyrogenesis

	addAppDeskbarSymlink $appsDir/0ad/pyrogenesis "0 A.D."
}

TEST()
{
	binaries/system/test -libdir "./binaries/system"
}
```

**Comment by Peppersawce** [comment]
> PROVIDES="
	0ad$secondaryArchSuffix = $portVersion
	app:0ad$secondaryArchSuffix = $portVersion
	lib:libcollada$secondaryArchSuffix
	lib:libnvcore$secondaryArchSuffix
	lib:libnvimage$secondaryArchSuffix
	lib:libnvmath$secondaryArchSuffix
	lib:libnvtt$secondaryArchSuffix
	"

At this point I think it makes more sense to have separate recipes for the included libraries, atm they're probably only needed for 0ad, but I wouldn't want to be in a situation where needing one of these libraries forces me to download > 1Gb of packages (since 0ad depends on its huge data package)

Also, is there a reason to be using boost 1.83 over newer versions? Is it the standard version atm?

**Comment by Begasus** [comment]
> At this point I think it makes more sense to have separate recipes for the included libraries, atm they're probably only needed for 0ad, but I wouldn't want to be in a situation where needing one of these libraries forces me to download > 1Gb of packages (since 0ad depends on its huge data package)
> 
> Also, is there a reason to be using boost 1.83 over newer versions? Is it the standard version atm?

I'm not sure how separating the libraries (which are part of 0ad) would benefit here? If you want to run 0ad you need the data (separate) package anyway (which is almost 2GB for the corresponding version btw.)

For boost, I haven't checked with a more recent version yet, so didn't change that (yet).

**Comment by Peppersawce** [comment]
> For boost, I haven't checked with a more recent version yet, so didn't change that (yet).

It builds with 1.88 at least, as I said in an earlier post.

> I'm not sure how separating the libraries (which are part of 0ad) would benefit here?

According to the info I'm looking for online, the nv** libraries are nvidia graphics-related and collada is related to documents, none of these seem 0ad-specific libraries and it could be a mess if any future port uses them as well.

**Comment by Begasus** [comment]
> According to the info I'm looking for online, the nv** libraries are nvidia graphics-related and collada is related to documents, none of these seem 0ad-specific libraries and it could be a mess if any future port uses them as well.

OK, so probably the nebula(?) driver from @X547 could be interfered by these then? If so, then yes, maybe move these into a sub-package?

**Comment by pulkomandy** [comment]
The libraries are developped by nvidia but not part of their drivers. They are just generic libraries to load and manipulate graphic textures.

I think this can stay as it is now until we find something else that uses these libraries. The packaging from NVidia is a bit unconvenient, and the lib is repackaged by the 0ad team, and is also patched in this recipe. So I'm not sure if this version is safe to use for other software that may need it. But there isn't such software in Haiku at the moment anyway.

I owuld say this is good enough to move past the libxml2 update which is the most pressing issue now, and nvtt handling can be reviewed later?

**Comment by Begasus** [comment]
Fine with me, done my share of testing ;) , if boost1.88 also works maybe move it  to that version, should at least drop some old requirements on 1.83.

**Comment by Peppersawce** [comment]
About the extra libraries, fair enough. About boost I'm pushing for using a newer version by now (building with 1.88 worked on my machine) so we're more future-proof. It's not necessary but I think it's going to be better for all of us in the long run.

Don't forget about updating the 0ad_data recipe as well, that one's required for the main package to work. You can find an updated recipe for it in one of my previous posts.

**Comment by pulkomandy** [comment]
Integrated all patches from the comments, looks all good to me.

File: dev-lang/spidermonkey/patches/spidermonkey-128.13.0.patchset [hunk 1]
```diff
@@ -0,0 +1,241 @@
...
+   static_assert(sizeof(pthread_mutex_t) / sizeof(void*) != 0 &&
+                     sizeof(pthread_mutex_t) % sizeof(void*) == 0,
+-- 
+2.54.0
+
+
+From 6d2ef6fffb627fcb6cee3568ea4b41b87391318e Mon Sep 17 00:00:00 2001
+From: PulkoMandy <pulkomandy@pulkomandy.tk>
+Date: Sat, 1 Aug 2026 10:49:10 +0200
+Subject: LEt another buildfile know about Haiku
```
Comment (OscarL) [inline dev-lang/spidermonkey/patches/spidermonkey-128.13.0.patchset]:
```suggestion
Subject: Let another buildfile know about Haiku
```

File: dev-util/premake/premake5-5.0.0~beta8.recipe [hunk 2]
```diff
@@ -44,11 +44,11 @@ BUILD_PREREQUIRES="
...
-PATCH()
-{
-	sed -i '/-lm/d' build/gmake2.unix/Premake5.make
-	sed -i 's/-rdynamic//g' build/gmake2.unix/Premake5.make
-}
+#PATCH()
+#{
+#	sed -i '/-lm/d' build/gmake2.unix/Premake5.make
+#	sed -i 's/-rdynamic//g' build/gmake2.unix/Premake5.make
+#}
```
Comment (OscarL) [inline dev-util/premake/premake5-5.0.0~beta8.recipe]: Could drop this and the commented PATCHES lines. Or add a comment about why they might be useful, in case they still could be?

File: games-strategy/0ad/0ad-0.28.0.recipe [hunk 3]
```diff
@@ -0,0 +1,134 @@
...
+	lib:libopenal$secondaryArchSuffix
+	lib:libpng16$secondaryArchSuffix
+	lib:libSDL2_2.0$secondaryArchSuffix
+	lib:libsodium$secondaryArchSuffix
+	lib:libssl$secondaryArchSuffix
+	lib:libvorbisfile$secondaryArchSuffix
+	lib:libxml2$secondaryArchSuffix
+	lib:libz$secondaryArchSuffix
+	0ad_data == $portVersion
+	"
```
Comment (OscarL) [inline games-strategy/0ad/0ad-0.28.0.recipe:47]:
```suggestion
REQUIRES="
	haiku$secondaryArchSuffix
	0ad_data == $portVersion
	lib:libcrypto$secondaryArchSuffix
	lib:libcurl$secondaryArchSuffix
	lib:libenet$secondaryArchSuffix
	lib:libfmt$secondaryArchSuffix
	lib:libfreetype$secondaryArchSuffix
	lib:libgloox$secondaryArchSuffix
	lib:libiconv$secondaryArchSuffix
	lib:libicui18n$secondaryArchSuffix
	lib:libicuuc$secondaryArchSuffix
	lib:libminiupnpc$secondaryArchSuffix
	lib:libmozjs_128$secondaryArchSuffix
	lib:libopenal$secondaryArchSuffix
	lib:libpng16$secondaryArchSuffix
	lib:libSDL2_2.0$secondaryArchSuffix
	lib:libsodium$secondaryArchSuffix
	lib:libssl$secondaryArchSuffix
	lib:libvorbisfile$secondaryArchSuffix
	lib:libxml2$secondaryArchSuffix
	lib:libz$secondaryArchSuffix
	"
```

Just to keep the "packages / cmds: / libs:" order we seem to generally maintain on these lists.

**Review by OscarL — APPROVED** [review]
Just some very trivial suggestions. Otherwise, LGTM. Thanks for tackling this one, folks!

File: dev-lang/spidermonkey/spidermonkey-128.13.0.recipe [hunk 4]
```diff
@@ -0,0 +1,91 @@
...
+
+BUILD()
+{
+	rm -rf /boot/home/.mozbuild
+	echo -e "ac_add_options --enable-optimize
+ac_add_options --enable-release
+mk_add_options MOZ_OBJDIR=obj-release" > mozconfig
+	MOZ_NOSPAM=1 MACH_BUILD_PYTHON_NATIVE_PACKAGE_SOURCE=none \
+		MOZCONFIG_OPTIONS="--with-system-zlib" \
+		python3.14 mach build $jobArgs
```
Comment (Begasus) [inline dev-lang/spidermonkey/spidermonkey-128.13.0.recipe]: Nitpicks:

```suggestion
		python$pythonVersion mach build $jobArgs
```

File: dev-lang/spidermonkey/spidermonkey-128.13.0.recipe [hunk 5]
```diff
@@ -0,0 +1,91 @@
...
+
+Name: SpiderMonkey 128.13.0
+Description: The Mozilla library for JavaScript
+Version: $portVersion
+Libs: -L$developLibDir -lmozjs-128
+Cflags: -I$includeDir
+EOF
+
+	prepareInstalledDevelLibs libmozjs-128
+	packageEntries devel $developDir
```
Comment (Begasus) [inline dev-lang/spidermonkey/spidermonkey-128.13.0.recipe]:
```suggestion
	prepareInstalledDevelLib \
		libmozjs-128

		packageEntries devel \
		$developDir
```

File: dev-util/premake/premake5-5.0.0~beta8.recipe [hunk 6]
```diff
@@ -3,16 +3,16 @@ DESCRIPTION="Describe your software project with a full-featured scripting \
...
-	premake5-$portVersion.patchset
-	"
+REVISION="1"
+SOURCE_URI="https://github.com/premake/premake-core/archive/refs/tags/v5.0.0-beta8.tar.gz"
+CHECKSUM_SHA256="2a55195fd2b27e5aa3de8ff6d22cdb127232a86f801d06e7f673d30a0eba09ac"
+SOURCE_DIR="premake-core-${portVersion/\~/-}"
+#PATCHES="
+#	premake-5.0.0-remove-hardcoded-libpath.patch
+#	premake5-5.0.0~beta2.patchset
+#	"
```
Comment (Begasus) [inline dev-util/premake/premake5-5.0.0~beta8.recipe]: Can be removed if not used.

**Review by Begasus — COMMENTED** [review]
Some nitpicks :)

File: dev-util/premake/premake5-5.0.0~beta8.recipe (hunk 2 above)
Comment (Begasus) [reply dev-util/premake/premake5-5.0.0~beta8.recipe]:
```suggestion

File: dev-util/premake/premake5-5.0.0~beta8.recipe (hunk 6 above)
Comment (Begasus) [reply dev-util/premake/premake5-5.0.0~beta8.recipe]:
```suggestion

```

**Review by Begasus — APPROVED** [review]
