### PR TITLE
pcsc_lite, update to version 2.4.1

### PR DESCRIPTION
**Pull request by Begasus**

### CODE REVIEW

**Comment by Begasus** [comment]
Error atm (can't figure this one out):
```
configfile.l: In function 'DBGetReaderListDir':
configfile.l:305:37: error: 'struct dirent' has no member named 'd_type'
  305 |                         if (direntry->d_type == DT_UNKNOWN)
      |                                     ^~
configfile.l:305:49: error: 'DT_UNKNOWN' undeclared (first use in this function); did you mean 'SCARD_UNKNOWN'?
  305 |                         if (direntry->d_type == DT_UNKNOWN)
      |                                                 ^~~~~~~~~~
      |                                                 SCARD_UNKNOWN
configfile.l:305:49: note: each undeclared identifier is reported only once for each function it appears in
configfile.l:324:45: error: 'struct dirent' has no member named 'd_type'
  324 |                                 if (direntry->d_type != DT_REG)
      |                                             ^~
configfile.l:324:57: error: 'DT_REG' undeclared (first use in this function)
  324 |                                 if (direntry->d_type != DT_REG)
      |     
```

**Comment by OscarL** [comment]
[This commit](https://github.com/LudovicRousseau/PCSC/commit/fa52ae4e1f1ae3c35596e9aedaa3ce30fc5ceef9) from 2016 fixed the lack of `d_type` on SunOS, but got reverted on [this other commit](https://github.com/LudovicRousseau/PCSC/commit/31a545adf79ce3134078b7f6a77b7665c9918976) in 2024 (and that's what breaks the build on pcsc-2.4.1 on Haiku now).

So, reverting the latter with:

```diff
From 95c8065da2afddfd975b7885691ad25ce927a733 Mon Sep 17 00:00:00 2001
From: Oscar Lesta <oscar.lesta@gmail.com>
Date: Tue, 12 May 2026 16:46:16 -0300
Subject: Revert upstream commit 31a545adf79ce3134078b7f6a77b7665c9918976.

The original change was needed on SunOS, but still works for making
Haiku builds succeed too.

diff --git a/src/configfile.l b/src/configfile.l
index fd44165..55e2fa2 100644
--- a/src/configfile.l
+++ b/src/configfile.l
@@ -301,8 +301,10 @@ int DBGetReaderListDir(const char *readerconf_dir,
 			snprintf(filename, sizeof(filename), "%s/%s",
 				readerconf_dir, direntry->d_name);
 
 			/* skip non regular files */
+#ifdef HAVE_STRUCT_DIRENT_D_TYPE
 			if (direntry->d_type == DT_UNKNOWN)
+#endif
 			{
 				struct stat st;
 
@@ -320,6 +322,7 @@ int DBGetReaderListDir(const char *readerconf_dir,
 					continue;
 				}
 			}
+#ifdef HAVE_STRUCT_DIRENT_D_TYPE
 			else
 				if (direntry->d_type != DT_REG)
 				{
@@ -327,6 +330,7 @@ int DBGetReaderListDir(const char *readerconf_dir,
 						direntry->d_name);
 					continue;
 				}
+#endif
 
 			/* skip files starting with . like ., .., .svn, etc */
 			if ('.' == direntry->d_name[0])
-- 
2.52.0
```

Seems enough to make the build succeed (well, on nightlies it complains about missing symbol for `issetugid`, so it needs adding `-lbsd` somewhere in there).

Edit... adding:

```diff
From c40423cf21e6c8db7e1d48e9f6643e82e219da8d Mon Sep 17 00:00:00 2001
From: Oscar Lesta <oscar.lesta@gmail.com>
Date: Tue, 12 May 2026 16:58:34 -0300
Subject: Check for issetugid() in libbsd.


diff --git a/configure.ac b/configure.ac
index 9ec7d46..f546907 100644
--- a/configure.ac
+++ b/configure.ac
@@ -140,6 +140,9 @@ AC_CHECK_LIB(socket, socket, [LIBS="$LIBS -lsocket"])
 # Check for the network library.
 AC_CHECK_LIB(network, socket, [LIBS="$LIBS -lnetwork"])
 
+# Haiku (post beta5) has issetugid() in libbsd
+AC_CHECK_LIB(bsd, issetugid, [LIBS="$LIBS -lbsd"])
+
 # check for mq_getattr()
 AC_CHECK_LIB(rt, mq_getattr, [LIBS="$LIBS -lrt"])
 
-- 
2.52.0
```

Helped with that, but then the build ends with:

```
/packages/pcsc_lite_devel-2.4.1-1/.self
Warning: POLICY ERROR: no matching provides "lib:libpcsclite_real" for "lib/libpcsclite_real.so"
Warning: POLICY ERROR: no matching provides "lib:libpcsclite_real" for "lib/libpcsclite_real.so.1"
Warning: POLICY ERROR: no matching provides "lib:libpcsclite_real" for "lib/libpcsclite_real.so.1.0.0"
```

So you'll still need to tweak the recipe a bit.

**Comment by Begasus** [comment]
> Edit... adding:

Missed that part after I already had it patched ;)
