### ISSUE TITLE
[git_svn] git svn doesn't work

### ISSUE THREAD

**Issue by soakbot** [haikuports/haikuports#111]
(Original issue 111 created by jessicah on 2014-09-09T01:43:34.705557+00:00)

```
~> git svn
Can't locate Git/SVN.pm in @INC (you may need to install the Git::SVN module) ...
BEGIN failed--compilation aborted at /packages/git-1.8.3.4-2/.self/lib/git-core/git-svn line 25.
****
```

**Comment by soakbot** [comment]
(Original comment by waddlesplash on 2014-09-12T00:22:28.872455+00:00)

Formatting...

**Comment by soakbot** [comment]
(Original comment by waddlesplash on 2014-09-24T17:25:39.801248+00:00)

I'm working on Git 2.1. Might as well get this along the way.

**Comment by soakbot** [comment]
(Original comment by Paradoxianer on 2015-03-10T22:48:36.436652+00:00)

it needs this wrapper from what i have found: https://metacpan.org/pod/Alien::SVN  maybe this helps.

**Comment by pulkomandy** [comment]
I managed to get alien_svn to build. But, it doesn't work: 

/Dev/Haiku/ports/dev-perl/alien_svn# git svn help
Can't load '/boot/system/lib/perl5/vendor_perl/5.18.2/BePC-haiku/auto/SVN/_Core/_Core.so' for module SVN::_Core: Missing library at /boot/system/lib/perl5/5.18.2/BePC-haiku/DynaLoader.pm line 190.
 at /boot/system/lib/perl5/vendor_perl/5.18.2/BePC-haiku/SVN/Base.pm line 59.
BEGIN failed--compilation aborted at /boot/system/lib/perl5/vendor_perl/5.18.2/BePC-haiku/SVN/Core.pm line 5.
Compilation failed in require at /boot/system/lib/perl5/vendor_perl/5.18.2/Git/SVN/Utils.pm line 6.
BEGIN failed--compilation aborted at /boot/system/lib/perl5/vendor_perl/5.18.2/Git/SVN/Utils.pm line 6.
Compilation failed in require at /boot/system/lib/perl5/vendor_perl/5.18.2/Git/SVN.pm line 32.
BEGIN failed--compilation aborted at /boot/system/lib/perl5/vendor_perl/5.18.2/Git/SVN.pm line 32.
Compilation failed in require at /packages/git-2.7.0-2/.self/lib/git-core/git-svn line 21.
BEGIN failed--compilation aborted at /packages/git-2.7.0-2/.self/lib/git-core/git-svn line 21.

**Comment by mmuman** [comment]
Btw, gentoo's subversion package does include Core.pm and other perl files:
http://www.portagefilelist.de/site/query/listPackageFiles/?category=dev-vcs&package=subversion&version=1.9.3&do#result

**Comment by mmuman** [comment]
Looks like we really need to uncomment the swig stuff in the subversion recipe.
