### PR TITLE
WIP: Update python packages for Python 3.14

### PR DESCRIPTION
**Pull request by pulkomandy**
When submitting changes to Haikuports, please check the following:

- [x] You are not a robot.
- [x] The modified recipe was confirmed to build on your Haiku machine.
- [ ] The license and copyright information in modified recipes are correct.
- [ ] The recipe follows one of the templates from https://github.com/haikuports/haikuporter/tree/master/generic (in particular, the fields are in the right [order](https://github.com/haikuports/haikuports/wiki/HaikuPorter-Guidelines#ordering)).
- [ ] The recipe is in the right category (matching Gentoo's overlays if the recipe is available there for example, use https://gpo.zugaina.org to search for existing recipes in Gentoo).

See the [guidelines](https://github.com/haikuports/haikuports/wiki/HaikuPorter-Guidelines) for more details.

### CODE REVIEW

**Comment by pulkomandy** [comment]
Doesn't build yet:

: && /bin/c++ -Wuninitialized -Wredundant-decls -Wall -Wno-invalid-offsetof -Wno-sign-compare -Wlogical-op -Winit-self -Wmissing-include-dirs -Wno-div-by-zero -Wtype-limits -Werror=return-type -Wno-char-subscripts -Wno-unknown-pragmas -Wpointer-arith -Wunused-parameter -Wwrite-strings -Wundef -Wformat-signedness -Wrestrict -Wno-suggest-override -Wuninitialized -Wundef -Wmissing-declarations -Wimplicit-fallthrough=5 -std=c++11 -fopenmp -msse -pipe -fPIC -funsigned-char -fno-strict-aliasing -ffp-contract=off -msse2 -fmacro-prefix-map="/sources/blender-3.3.21/"="" -fmacro-prefix-map="/sources/blender-3.3.21/build_haiku/"="" -Wno-maybe-uninitialized -O2 -DNDEBUG -no-pie    -Wl,--version-script='/sources/blender-3.3.21/source/creator/symbols_unix.map' source/creator/CMakeFiles/blender.dir/creator.c.o source/creator/CMakeFiles/blender.dir/creator_args.c.o source/creator/CMakeFiles/blender.dir/creator_signals.c.o -o bin/blender  lib/libbf_windowmanager.a  -lnetwork  -liconv  -licuuc  -licui18n  lib/libbf_editor_screen.a  lib/libbf_sequencer.a  lib/libbf_compositor.a  lib/libbf_editor_space_sequencer.a  lib/libbf_blenkernel.a  lib/libbf_editor_interface.a  lib/libbf_blenloader.a  lib/libbf_blentranslation.a  lib/libbf_bmesh.a  lib/libbf_depsgraph.a  lib/libbf_draw.a  lib/libbf_imbuf.a  lib/libbf_modifiers.a  lib/libbf_nodes.a  lib/libbf_rna.a  lib/libbf_simulation.a  lib/libbf_python.a  lib/libbf_python_bmesh.a  lib/libbf_alembic.a  lib/libbf_nodes_geometry.a  lib/libbf_nodes_shader.a  lib/libbf_nodes_texture.a  lib/libbf_editor_space_api.a  lib/libbf_editor_animation.a  lib/libbf_editor_armature.a  lib/libbf_editor_asset.a  lib/libbf_editor_curve.a  lib/libbf_editor_curves.a  lib/libbf_editor_gpencil.a  lib/libbf_editor_io.a  lib/libbf_editor_mesh.a  lib/libbf_editor_object.a  lib/libbf_editor_physics.a  lib/libbf_editor_scene.a  lib/libbf_editor_sculpt_paint.a  lib/libbf_editor_sound.a  lib/libbf_editor_transform.a  lib/libbf_editor_undo.a  lib/libbf_python_mathutils.a  lib/libbf_io_common.a  lib/libbf_geometry.a  lib/libbf_editor_geometry.a  lib/libbf_editor_space_action.a  lib/libbf_editor_space_clip.a  lib/libbf_editor_space_console.a  lib/libbf_editor_space_file.a  lib/libbf_editor_space_graph.a  lib/libbf_editor_space_image.a  lib/libbf_editor_space_nla.a  lib/libbf_editor_space_node.a  lib/libbf_editor_space_outliner.a  lib/libbf_editor_space_statusbar.a  lib/libbf_editor_space_text.a  lib/libbf_editor_space_view3d.a  lib/libbf_wavefront_obj.a  lib/libbf_stl.a  lib/libbf_gpencil.a  lib/libbf_render.a  lib/libbf_editor_uvedit.a  lib/libbf_freestyle.a  lib/libbf_windowmanager.a  lib/libbf_editor_screen.a  lib/libbf_sequencer.a  lib/libbf_compositor.a  lib/libbf_editor_space_sequencer.a  lib/libbf_blenkernel.a  lib/libbf_editor_interface.a  lib/libbf_blenloader.a  lib/libbf_blentranslation.a  lib/libbf_bmesh.a  lib/libbf_depsgraph.a  lib/libbf_draw.a  lib/libbf_imbuf.a  lib/libbf_modifiers.a  lib/libbf_nodes.a  lib/libbf_rna.a  lib/libbf_simulation.a  lib/libbf_python.a  lib/libbf_python_bmesh.a  lib/libbf_alembic.a  lib/libbf_nodes_geometry.a  lib/libbf_nodes_shader.a  lib/libbf_nodes_texture.a  lib/libbf_editor_space_api.a  lib/libbf_editor_animation.a  lib/libbf_editor_armature.a  lib/libbf_editor_asset.a  lib/libbf_editor_curve.a  lib/libbf_editor_curves.a  lib/libbf_editor_gpencil.a  lib/libbf_editor_io.a  lib/libbf_editor_mesh.a  lib/libbf_editor_object.a  lib/libbf_editor_physics.a  lib/libbf_editor_scene.a  lib/libbf_editor_sculpt_paint.a  lib/libbf_editor_sound.a  lib/libbf_editor_transform.a  lib/libbf_editor_undo.a  lib/libbf_python_mathutils.a  lib/libbf_io_common.a  lib/libbf_geometry.a  lib/libbf_editor_geometry.a  lib/libbf_editor_space_action.a  lib/libbf_editor_space_clip.a  lib/libbf_editor_space_console.a  lib/libbf_editor_space_file.a  lib/libbf_editor_space_graph.a  lib/libbf_editor_space_image.a  lib/libbf_editor_space_nla.a  lib/libbf_editor_space_node.a  lib/libbf_editor_space_outliner.a  lib/libbf_editor_space_statusbar.a  lib/libbf_editor_space_text.a  lib/libbf_editor_space_view3d.a  lib/libbf_wavefront_obj.a  lib/libbf_stl.a  lib/libbf_gpencil.a  lib/libbf_render.a  lib/libbf_editor_uvedit.a  lib/libbf_freestyle.a  lib/libextern_clew.a  lib/libbf_editor_util.a  lib/libbf_gpencil_modifiers.a  lib/libbf_ikplugin.a  lib/libbf_intern_iksolver.a  lib/libbf_intern_itasc.a  lib/libbf_intern_clog.a  lib/libbf_intern_ghost.a  lib/libbf_intern_glew_mx.a  lib/libbf_intern_libmv.a  lib/libextern_ceres.a  lib/libextern_glog.a  lib/libextern_gflags.a  lib/libbf_intern_mikktspace.a  lib/libbf_intern_opensubdiv.a  lib/libbf_shader_fx.a  lib/libbf_intern_rigidbody.a  /boot/system/develop/lib/liblzo2.so  lib/libextern_lzma.a  /boot/system/develop/lib/libfftw3.so  /boot/system/develop/lib/libosdGPU.so  /boot/system/develop/lib/libosdCPU.so  lib/libbf_intern_quadriflow.a  lib/libextern_quadriflow.a  lib/libbf_intern_locale.a  lib/libextern_rangetree.a  lib/libbf_intern_memutil.a  lib/libbf_intern_opencolorio.a  /boot/system/develop/lib/libOpenColorIO.so  /boot/system/develop/lib/libyaml-cpp.so  /boot/system/develop/lib/libpystring.so  lib/libbf_imbuf_openimageio.a  /boot/system/develop/lib/libOpenImageIO.so  /boot/system/develop/lib/libOpenImageIO_Util.so  /boot/system/develop/lib/libpng.so  /boot/system/develop/lib/libtiff.so  /boot/system/develop/lib/libopenjp2.so  lib/libbf_avi.a  /boot/system/develop/lib/libjpeg.so  lib/libbf_imbuf_dds.a  lib/libbf_imbuf_cineon.a  /boot/system/develop/lib/libwebp.so  /boot/system/develop/lib/libwebpmux.so  /boot/system/develop/lib/libwebpdemux.so  /boot/system/develop/lib/libsharpyuv.so  lib/libbf_intern_dualcon.a  lib/libbf_nodes_composite.a  lib/libbf_nodes_function.a  lib/libbf_dna.a  lib/libbf_editor_gizmo_library.a  lib/libbf_editor_render.a  lib/libbf_python_gpu.a  /boot/system/develop/lib/libAlembic.so  lib/libextern_bullet.a  lib/libbf_functions.a  lib/libbf_intern_sky.a  lib/libbf_editor_space_buttons.a  lib/libbf_editor_space_info.a  lib/libbf_editor_space_script.a  lib/libbf_editor_space_spreadsheet.a  lib/libbf_editor_space_topbar.a  lib/libbf_editor_space_userpref.a  lib/libextern_curve_fit_nd.a  /boot/system/develop/lib/libpotrace.so  lib/libbf_collada.a  /boot/system/lib/libOpenCOLLADAStreamWriter.so  /boot/system/lib/libOpenCOLLADASaxFrameworkLoader.so  /boot/system/lib/libOpenCOLLADAFramework.so  /boot/system/lib/libOpenCOLLADABaseUtils.so  /boot/system/lib/libGeneratedSaxParser.so  /boot/system/lib/libMathMLSolver.so  /boot/system/lib/libbuffer.so  /boot/system/lib/libftoa.so  /boot/system/lib/libUTF.so  /boot/system/develop/lib/libpcre.so  /boot/system/develop/lib/libxml2.so  lib/libbf_blenfont.a  /boot/system/develop/lib/libfreetype.so  lib/libbf_gpu.a  lib/libbf_draw_shaders.a  /boot/system/lib/libGL.so  lib/libextern_glew.a  lib/libbf_gpu_shaders.a  lib/libbf_ocio_shaders.a  lib/libbf_editor_mask.a  lib/libbf_editor_metaball.a  lib/libbf_python_ext.a  lib/libbf_editor_datafiles.a  lib/libbf_intern_audaspace.a  lib/libaudaspace.a  -lpthread  /boot/system/develop/lib/libavcodec.so  /boot/system/develop/lib/libavdevice.so  /boot/system/develop/lib/libavfilter.so  /boot/system/develop/lib/libavformat.so  /boot/system/develop/lib/libavutil.so  /boot/system/develop/lib/libswscale.so  /boot/system/develop/lib/libswresample.so  /boot/system/develop/lib/libsndfile.so  /boot/system/develop/lib/libopenal.so  /boot/system/develop/lib/libSDL2.so  lib/libbf_editor_lattice.a  lib/libbf_blenlib.a  lib/libbf_intern_guardedalloc.a  lib/libbf_intern_eigen.a  lib/libextern_wcwidth.a  /boot/system/lib/libz.so.1  /boot/system/develop/lib/libzstd.so  /boot/system/develop/lib/libgmpxx.so  /boot/system/develop/lib/libgmp.so  lib/libbf_intern_libc_compat.a  /packages/boost1.83-1.83.0-5/.self/lib/libboost_filesystem.so.1.83.0  /packages/boost1.83-1.83.0-5/.self/lib/libboost_atomic.so.1.83.0  /packages/boost1.83-1.83.0-5/.self/lib/libboost_regex.so.1.83.0  /packages/boost1.83-1.83.0-5/.self/lib/libboost_date_time.so.1.83.0  /packages/boost1.83-1.83.0-5/.self/lib/libboost_locale.so.1.83.0  /packages/boost1.83-1.83.0-5/.self/lib/libboost_thread.so.1.83.0  /packages/boost1.83-1.83.0-5/.self/lib/libboost_chrono.so.1.83.0  /packages/boost1.83-1.83.0-5/.self/lib/libboost_system.so.1.83.0  /boot/system/develop/lib/libpugixml.so  /boot/system/develop/lib/libhpdf.so  lib/libbf_imbuf_openexr.a  /boot/system/develop/lib/libIex-3_2.so  /boot/system/develop/lib/libOpenEXR-3_2.so  /boot/system/develop/lib/libImath.so  /boot/system/develop/lib/libIlmThread-3_2.so  /boot/system/develop/lib/libImath-3_1.so  -Xlinker -export-dynamic  /boot/system/lib/libpython3.10.so.1.0 && :
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/13.3.0/../../../../x86_64-unknown-haiku/bin/ld: lib/libbf_alembic.a(abc_writer_transform.cc.o): in function `blender::io::alembic::ABCTransformWriter::do_write(blender::io::HierarchyContext&)':
abc_writer_transform.cc:(.text+0xa88): undefined reference to `Alembic::AbcGeom::v12::XformSample::setMatrix(Imath_3_1::Matrix44<double> const&)'


But if the approach seems OK I can push the first commits to master already, until this can be solved. Time to sleep for now...

**Comment by waddlesplash** [comment]
Non-WIP commits look good to me.

**Comment by OscarL** [comment]
So far we have being introducing new 3.14 packages with a dotted-version suffix (`_python3.14` vs `_python310`). (to avoid having to add REPLACES in the future).

Example of such change: https://github.com/haikuports/haikuports/commit/13e58fa76008d6c8e08889b9594c5ec5c8797056

In any case, not a show-stopper, just a note.

**Comment by OscarL** [comment]
`tomli` is not really needed post Python 3.10, as since 3.11, it is part of Python's standard library.

(any recipes targetting 3.14 should just drop tomli from REQUIRES)

**Comment by OscarL** [comment]
FWIW, I can work on the `dev-python/*/*` recipes touched here, and propose a PR for them. I'll get to it.

**Comment by pulkomandy** [comment]
OK, they turned out to not be really needed anyway because our Blender doesn't build with Python 3.14. So this is not really a priority after all (I am kind of exploring options and trying different things here, but also I ran into a problem that numpy wouldn't be found on the second build attempt, which I "fixed" by adding an rm -rf at the start of the build).

I guess we'll have to look into updating Blender to a newer version, but maybe after the libxml2 problems are cleaned up, I don't want to get into too much big changes at the same time.

**Comment by OscarL** [comment]
> I don't want to get into too much big changes at the same time.

Same here. Trying to fix problems related to the 3.10 to 3.14 Python change as they appear, but kicking the bulk of packages migration for "post-beta6" as much as possible :-)

**Comment by OscarL** [comment]
Blender3 build finally [made it](https://build.haiku-os.org/buildmaster/master/x86_64/?buildrunDir=14888&viewMode=expanded), without needing these rev-bumps or introducing `*_python314` packages yet.

Maybe we can close this, and instead add `_python3.14` (mind the dot :-P), in the (hopefully) near future, while also updating the recipes? (I hope I'll be able to tackle these as needed).

Thanks @pulkomandy and @Begasus!

**Comment by pulkomandy** [comment]
I rebased this to keep only the Python 3.14 changes, which indeed were not needed for Blender eventually (the version we use currently fails to build with newer Python versions, we'll need to update it).

Do with these changes as you want, I have tested that these recipes build fine, but didn't use them further in the end. And surely we can do with some re-synchronization of the template for Python recipes, as some of them jave a working default packages, some not, and a few other minor variants.
